"""Re-add table morphological_paradigms

Revision ID: 01be7e7dff09
Revises: b81012db2ba2
Create Date: 2019-07-01 10:19:11.962835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01be7e7dff09'
down_revision = 'b81012db2ba2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morphological_paradigms',
    sa.Column('paradigm_id', sa.BigInteger().with_variant(sa.Integer, "sqlite"), nullable=False),
    sa.Column('Z', sa.BigInteger(), nullable=True),
    sa.Column('Y', sa.BigInteger(), nullable=True),
    sa.Column('X', sa.BigInteger(), nullable=True),
    sa.Column('W', sa.BigInteger(), nullable=True),
    sa.Column('V', sa.BigInteger(), nullable=True),
    sa.Column('word_type_code', sa.String(length=10), nullable=True),
    sa.Column('word_type_number', sa.BigInteger(), nullable=True),
    sa.Column('wordform_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['wordform_id'], ['wordforms.wordform_id'], ),
    sa.PrimaryKeyConstraint('paradigm_id')
    )
    op.create_index(op.f('ix_morphological_paradigms_V'), 'morphological_paradigms', ['V'], unique=False)
    op.create_index(op.f('ix_morphological_paradigms_W'), 'morphological_paradigms', ['W'], unique=False)
    op.create_index(op.f('ix_morphological_paradigms_X'), 'morphological_paradigms', ['X'], unique=False)
    op.create_index(op.f('ix_morphological_paradigms_Y'), 'morphological_paradigms', ['Y'], unique=False)
    op.create_index(op.f('ix_morphological_paradigms_Z'), 'morphological_paradigms', ['Z'], unique=False)
    op.create_index(op.f('ix_morphological_paradigms_word_type_code'), 'morphological_paradigms', ['word_type_code'], unique=False)
    op.create_index(op.f('ix_morphological_paradigms_word_type_number'), 'morphological_paradigms', ['word_type_number'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_morphological_paradigms_word_type_number'), table_name='morphological_paradigms')
    op.drop_index(op.f('ix_morphological_paradigms_word_type_code'), table_name='morphological_paradigms')
    op.drop_index(op.f('ix_morphological_paradigms_Z'), table_name='morphological_paradigms')
    op.drop_index(op.f('ix_morphological_paradigms_Y'), table_name='morphological_paradigms')
    op.drop_index(op.f('ix_morphological_paradigms_X'), table_name='morphological_paradigms')
    op.drop_index(op.f('ix_morphological_paradigms_W'), table_name='morphological_paradigms')
    op.drop_index(op.f('ix_morphological_paradigms_V'), table_name='morphological_paradigms')
    op.drop_table('morphological_paradigms')
    # ### end Alembic commands ###
