"""add_morph_paradigms_table

Revision ID: 0cba7290cb2a
Revises: e3edd86918fd
Create Date: 2019-06-28 14:46:42.382433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cba7290cb2a'
down_revision = 'e3edd86918fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morph_paradigms',
    sa.Column('wordform_id', sa.BigInteger(), nullable=False),
    sa.Column('Z', sa.BigInteger(), nullable=True),
    sa.Column('Y', sa.BigInteger(), nullable=True),
    sa.Column('X', sa.BigInteger(), nullable=True),
    sa.Column('W', sa.BigInteger(), nullable=True),
    sa.Column('V', sa.BigInteger(), nullable=True),
    sa.Column('word_type_code', sa.String(length=10), nullable=True),
    sa.Column('pos', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['wordform_id'], ['wordforms.wordform_id'], ),
    sa.PrimaryKeyConstraint('wordform_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morph_paradigms')
    # ### end Alembic commands ###
