"""Temporarily delete morphological_paradigms

Revision ID: b81012db2ba2
Revises: e3edd86918fd
Create Date: 2019-06-28 09:34:58.033542

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b81012db2ba2'
down_revision = 'e3edd86918fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morphological_paradigms')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morphological_paradigms',
    sa.Column('Z', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('Y', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('X', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('W', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('V', mysql.BIGINT(display_width=20), autoincrement=False, nullable=False),
    sa.Column('wordform_id', mysql.BIGINT(display_width=20), autoincrement=False, nullable=True),
    sa.Column('word_type_code', mysql.VARCHAR(collation='utf8mb4_bin', length=10), nullable=False),
    sa.Column('pos', mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_bin', length=10), nullable=True),
    sa.ForeignKeyConstraint(['wordform_id'], ['wordforms.wordform_id'], name='morphological_paradigms_ibfk_1'),
    sa.PrimaryKeyConstraint('Z', 'Y', 'X', 'W', 'V'),
    mysql_collate='utf8mb4_bin',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
