"""Add the morphological_links table

Revision ID: e2830294c0dd
Revises: 
Create Date: 2019-06-26 13:22:51.981921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2830294c0dd'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('morphological_links',
    sa.Column('Z', sa.BigInteger().with_variant(sa.Integer, 'sqlite'), 
              nullable=False),
    sa.Column('Y', sa.BigInteger().with_variant(sa.Integer, 'sqlite'), 
              nullable=False),
    sa.Column('X', sa.BigInteger().with_variant(sa.Integer, 'sqlite'), 
              nullable=False),
    sa.Column('W', sa.BigInteger().with_variant(sa.Integer, 'sqlite'), 
              nullable=False),
    sa.Column('V', sa.BigInteger().with_variant(sa.Integer, 'sqlite'), 
              nullable=False),
    sa.Column('wordform_id', sa.BigInteger(), nullable=True),
    sa.Column('pos', sa.String(length=10), nullable=True),
    sa.Column('word_type_code', sa.String(length=10), nullable=True),
    sa.ForeignKeyConstraint(['wordform_id'], ['wordforms.wordform_id'], ),
    sa.PrimaryKeyConstraint('Z', 'Y', 'X', 'W', 'V')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('morphological_links')
    # ### end Alembic commands ###
