"""Add ld and anahash_difference fields

Revision ID: fecf6a206bfc
Revises:
Create Date: 2019-08-13 14:48:21.544018

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fecf6a206bfc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('source_x_wordform_link', sa.Column('anahash_difference', sa.BigInteger(), nullable=True))
    op.add_column('source_x_wordform_link', sa.Column('ld', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('source_x_wordform_link', 'ld')
    op.drop_column('source_x_wordform_link', 'anahash_difference')
    # ### end Alembic commands ###
